language: node_js
node_js:
  - 10
  - 12
cache:
  directories:
    - "node_modules"
before_install:
  - wget https://www.antlr.org/download/antlr-4.7.2-complete.jar --directory-prefix handledom
env:
  - SUB_PROJECT=handledom
script: cd $SUB_PROJECT && npm i && npm run prepublishOnly
